# Dedicated config for a demo client process.

mode = "client"
host = "127.0.0.1"
port = 45500
jobs = 9

caf {
  middleman {
    enable-automatic-connections = false
    app-identifiers = ["distributed-actors-codex"]
    heartbeat-interval = 0ms
  }
  logger {
    console {
      format = "[%c:%p] %d %m"
      verbosity = "trace"
    }
  }
}
