mode = "client"
name = "client"
master-host = "127.0.0.1"
master-port = 46000
region = "region-a"
storage-key = "profile"

caf {
  middleman {
    enable-automatic-connections = false
    app-identifiers = ["distributed-nodes"]
    heartbeat-interval = 0ms
  }
  logger {
    console {
      format = "[%c:%p] %d %m"
      verbosity = "info"
    }
  }
}
