mode = "compute"
name = "compute-a1"
host = "127.0.0.1"
port = 46011
master-host = "127.0.0.1"
master-port = 46000
parent = "region-a"
lifetime = 0

caf {
  middleman {
    enable-automatic-connections = false
    app-identifiers = ["distributed-nodes"]
    heartbeat-interval = 0ms
  }
  logger {
    console {
      format = "[%c:%p] %d %m"
      verbosity = "info"
    }
  }
}
